/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PlatformService } from "../platform.service";
import { PlatformCreateInput } from "./PlatformCreateInput";
import { Platform } from "./Platform";
import { PlatformFindManyArgs } from "./PlatformFindManyArgs";
import { PlatformWhereUniqueInput } from "./PlatformWhereUniqueInput";
import { PlatformUpdateInput } from "./PlatformUpdateInput";

export class PlatformControllerBase {
  constructor(protected readonly service: PlatformService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Platform })
  async createPlatform(
    @common.Body() data: PlatformCreateInput
  ): Promise<Platform> {
    return await this.service.createPlatform({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        platformName: true,
        apiUrl: true,
        apiKey: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Platform] })
  @ApiNestedQuery(PlatformFindManyArgs)
  async platforms(@common.Req() request: Request): Promise<Platform[]> {
    const args = plainToClass(PlatformFindManyArgs, request.query);
    return this.service.platforms({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        platformName: true,
        apiUrl: true,
        apiKey: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Platform })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async platform(
    @common.Param() params: PlatformWhereUniqueInput
  ): Promise<Platform | null> {
    const result = await this.service.platform({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        platformName: true,
        apiUrl: true,
        apiKey: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Platform })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePlatform(
    @common.Param() params: PlatformWhereUniqueInput,
    @common.Body() data: PlatformUpdateInput
  ): Promise<Platform | null> {
    try {
      return await this.service.updatePlatform({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          platformName: true,
          apiUrl: true,
          apiKey: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Platform })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePlatform(
    @common.Param() params: PlatformWhereUniqueInput
  ): Promise<Platform | null> {
    try {
      return await this.service.deletePlatform({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          platformName: true,
          apiUrl: true,
          apiKey: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
